### PR TITLE
Fix #129 nullptr_t changed to std::nullptr_t

### LINKED ISSUE #129: Clang error: Unknown type name 'nullptr_t'; did you mean 'std::nullptr_t'?
Today I've pulled a Selene and I've got this error:
```
In file included from /home/drmgc/sandbox/mmltest/src/game.cpp:7:
In file included from /home/drmgc/sandbox/mmltest/src/game.hpp:9:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene.h:7:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/State.h:7:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/Registry.h:3:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/Class.h:3:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/ClassFun.h:3:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/BaseFun.h:3:
In file included from /home/drmgc/sandbox/mmltest/3rd/selene/include/selene/function.h:6:
/home/drmgc/sandbox/mmltest/3rd/selene/include/selene/references.h:64:28: error: C++ requires a type specifier for all declarations
    friend bool operator==(nullptr_t, Pointer<T> const & ptr) {
                           ^~~~~~~~~
/home/drmgc/sandbox/mmltest/3rd/selene/include/selene/references.h:68:52: error: unknown type name 'nullptr_t'; did you mean
      'std::nullptr_t'?
    friend bool operator==(Pointer<T> const & ptr, nullptr_t) {
                                                   ^~~~~~~~~
                                                   std::nullptr_t 
```

### PR DESCRIPTION
**Pull request by drmgc**
Fix issue #129

### CODE REVIEW

**Comment by AnonymousProgrammerLandau** [comment]
I also found this by now. Did not understand why that actually is a problem, since all include chains leading to `references.h` have already included `lua.h`, which in my implementation already includes `stddef.h` and consequently should deliver `nullptr_t` in the global namespace.

Apart from that I would actually include `cstdint` in `references.h`.

**Comment by drmgc** [comment]
Well, `nullptr_t` is member of `std` namespace. Using `using namespace` (even `using namespace std;`) in headers is bad practice, so in headers `std::nullptr_t` must be, not `nullptr_t`

**Comment by AnonymousProgrammerLandau** [comment]
The **C** header `stddef.h` of my compiler actually has `nullptr_t` in global namespace. Surely no `using namespace std` in headers.

**Comment by drmgc** [comment]
In my OS, `stddef.h` (that places in `/usr/include/linux`) is empty. And `cstddef` contain only this
```c++
#ifndef _GLIBCXX_CSTDDEF
#define _GLIBCXX_CSTDDEF 1

#pragma GCC system_header

#include <bits/c++config.h>
#include <stddef.h>

#if __cplusplus >= 201103L
namespace std
{
  // We handle size_t, ptrdiff_t, and nullptr_t in c++config.h.
  using ::max_align_t;
}
#endif

#endif // _GLIBCXX_CSTDDEF
```

**Pull request merged**
